@startuml
class inf319.exercise09.Queue {
- {static} int DEFAULTQUEUESIZE
- int queueMaxSize
- int front
- int rear
- Object[] queue
+ boolean enqueue(Object)
+ Object dequeue()
+ int remaining()
+ int size()
+ int maxSize()
+ boolean empty()
}


class inf319.exercise09.Stack {
- Queue queue
+ boolean push(Object)
+ Object pop()
+ int size()
+ int maxSize()
+ int remaining()
+ boolean empty()
}

inf319.exercise09.Queue --> inf319.exercise09.Stack
@enduml